Matsu.CoreSample.Web/Models/ErrorViewModel.cs
namespace Matsu.CoreSample.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Matsu.CoreSample.Web/Models/KeyValue.cs
namespace Matsu.CoreSample.Web.Models
{
    public class KeyValue
    {
        public int id { get; set; }
        public string name { get; set; }
        public string value { get; set; }
    }
}

Matsu.CoreSample.Web/Controllers/HomeController.cs
using Matsu.CoreSample.Common;
using Matsu.CoreSample.Common.Domain.Users;
using Matsu.CoreSample.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Diagnostics;

namespace Matsu.CoreSample.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUserService _userService;

        public HomeController(ILogger<HomeController> logger, IUserService userService)
        {
            _logger = logger;
            _userService = userService;
        }

        public IActionResult Index()
        {
            var result = GetDbResults();
            return View("Index", result);
        }

        public string GetDbResults()
        {
            return _userService.Get("1").Name;
        }

        //public string GetWorkFlowResults()
        //{
        //    var api = new LogicAppsStandardWebApi();
        //    var result = api.CallHttpTrigger("https://la4standard.azurewebsites.net:443/api/WF-HTTPtrigger/triggers/manual/invoke?api-version=2022-05-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0", "tFJChuAq-AwUYqVJIOrtFrsGlQcqG7QA3JiXE6YhB0c").Result.ToString();
        //    return $"Time from Logic Apps: {result}";
        //}

        public string GetApiResults()
        {
            return "Success App Service Api Call!";
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Matsu.CoreSample.Web/Controllers/KeyValuesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Matsu.CoreSample.Common.Database.Models;
using Matsu.CoreSample.Common.Database.Data;
using System.Linq;

namespace Matsu.CoreSample.Web.Controllers
{
    public class KeyValuesController : Controller
    {
        private readonly SqlServerCustomContext _context;
        private readonly ILogger _logger;

        public KeyValuesController(SqlServerCustomContext context, ILogger<KeyValuesController> logger)
        {
            _context = context;
            _logger = logger;
        }

        // GET: KeyValues
        public async Task<IActionResult> Index()
        {
            _logger.LogWarning("[CustomLog] Matsu.CoreSample.Web.Controllers.KeyValuesController - Index");
            return _context.KeyValue != null ?
                View(await _context.KeyValue.ToListAsync()) :
                Problem("Entity set 'MyDatabaseContext.KeyValue'  is null.");
        }

        // GET: KeyValues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.KeyValue == null)
            {
                return NotFound();
            }

            var keyValue = await _context.KeyValue
                .FirstOrDefaultAsync(m => m.id == id);
            if (keyValue == null)
            {
                return NotFound();
            }

            return View(keyValue);
        }

        // GET: KeyValues/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: KeyValues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,value")] KeyValue keyValue)
        {
            if (ModelState.IsValid)
            {
                keyValue.id = _context.KeyValue.Max(m => m.id) + 1;
                _context.Add(keyValue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(keyValue);
        }

        // GET: KeyValues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.KeyValue == null)
            {
                return NotFound();
            }

            var keyValue = await _context.KeyValue.FindAsync(id);
            if (keyValue == null)
            {
                return NotFound();
            }
            return View(keyValue);
        }

        // POST: KeyValues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,name,value")] KeyValue keyValue)
        {
            if (id != keyValue.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(keyValue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KeyValueExists(keyValue.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(keyValue);
        }

        // GET: KeyValues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.KeyValue == null)
            {
                return NotFound();
            }

            var keyValue = await _context.KeyValue
                .FirstOrDefaultAsync(m => m.id == id);
            if (keyValue == null)
            {
                return NotFound();
            }

            return View(keyValue);
        }

        // POST: KeyValues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.KeyValue == null)
            {
                return Problem("Entity set 'MyDatabaseContext.KeyValue'  is null.");
            }
            var keyValue = await _context.KeyValue.FindAsync(id);
            if (keyValue != null)
            {
                _context.KeyValue.Remove(keyValue);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KeyValueExists(int id)
        {
            return (_context.KeyValue?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Matsu.CoreSample.Web/Views/Home/Index.cshtml
@model string
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>@Model</p>
</div>

Matsu.CoreSample.Web/Views/KeyValues/Create.cshtml
@using Matsu.CoreSample.Common.Database.Models;
@model KeyValue

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>KeyValue</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="value" class="control-label"></label>
                <input asp-for="value" class="form-control" />
                <span asp-validation-for="value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Matsu.CoreSample.Web/Views/KeyValues/Delete.cshtml
@using Matsu.CoreSample.Common.Database.Models;
@model KeyValue

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KeyValue</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.value)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.value)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Matsu.CoreSample.Web/Views/KeyValues/Details.cshtml
@using Matsu.CoreSample.Common.Database.Models;
@model KeyValue

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>KeyValue</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.value)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.value)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Matsu.CoreSample.Web/Views/KeyValues/Edit.cshtml
@using Matsu.CoreSample.Common.Database.Models;
@model KeyValue

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>KeyValue</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="value" class="control-label"></label>
                <input asp-for="value" class="form-control" />
                <span asp-validation-for="value" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Matsu.CoreSample.Web/Views/KeyValues/Index.cshtml
@using Matsu.CoreSample.Common.Database.Models;
@model IEnumerable<KeyValue>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.value)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.value)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Matsu.CoreSample.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Matsu.CoreSample.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Matsu.CoreSample.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Matsu.CoreSample.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="KeyValues" asp-action="Index">Key Values</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Matsu.CoreSample.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>